spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb+srv://admin:Poorvi%40123@cluster0.wr9ar1h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: fitnessactivity

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


