spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/fitness_user_db
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

